import mongoose, { Schema } from "mongoose"

const productSchema=new Schema({
    name:{
        type:String,
        required:true,
        trim:true
    },
    description:{
        type:String
    },
    category:{
        type:String,
        required:true
    },
    colors:{
        type:[String]
    },
    images:{
        type:[String]
    },
    totalStock:{
        type:Number,
        required:true,
        min:0
    },
    availableStock:{
        type:Number,
        required:true,
        min:0
    },
    pricing:{
        type:{
            perHour:{
                type:Number,
                default:0
            },
            perDay:{
                type:Number,
                default:0
            },
            perWeek:{
                type:Number,
                default:0
            },
            perMonth:{
                type:Number,
                default:0
            }
        }
    },
    extraHourCharge:{
        type:Number,
        default:0
    },
    extraDayCharge:{
        type:Number,
        default:0
    },
    depositAmount:{
        type:Number,
        default:0
    },
    lateFeePerDay:{
        type:Number,
        default:0
    },
    taxPercent:{
        type:Number,
        default:0
    },
    isAvailable:{
        type:Boolean,
        default:true
    },
    averageRating:{
        type:Number,
        default:0
    },
    totalReviews:{
        type:Number,
        default:0
    }
},{timestamps:true});

export const Product =mongoose.model("Product",productSchema);