import mongoose,{Schema} from "mongoose";

const rentalOrderSchema=new Schema({
    orderId:{
        type:String,
        unique:true,
        required: true
    },
    customer:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"User",
        required:true
    },
    items:{
        type:[
            {
                product:{
                    type:mongoose.Schema.Types.ObjectId,
                    ref:"Product",
                    required:true
                },
                quantity:{
                    type:Number,
                    min:1,
                    required:true
                },
                unitPrice:{
                    type:Number,
                    required:true
                },
                subTotal:{
                    type:Number,
                    required:true
                },
                tax:{
                    type:Number,
                    default:0
                }
            }
        ],
        validate: {
            validator: (value) => value.length > 0,
            message: "Rental order must contain at least one item.",
        }
    },
    startDate:{
        type:Date,
        required:true
    },
    endDate:{
        type:Date,
        required:true
    },
    actualReturnDate:{
        type:Date
    },
    durationType:{
        type:String,
        enum:["hourly","daily","weekly","monthly"]
    },
    deliveryAddress:{
        type:String,   
    },
    invoiceAddress:{
        type:String
    },
    deliveryMethod:{
        type:String,
        enum:["pickup","home_delivery"],
        default:"pickup"
    },
    deliveryCharge:{
        type:Number,
        default:0
    },
    couponCode:{
        type:String
    },
    couponDiscount:{
        type:Number,
        default:0
    },
    subTotal:{
        type:Number,
    },
    taxAmount:{
        type:Number,
    },
    depositAmount:{
        type:Number,
        default:0
    },
    lateFeeAmount:{
        type:Number,
        default:0
    },
    totalAmount:{
        type:Number
    },
    rentalStatus:{
        type:String,
        enum:["quotation","quotation_sent","reserved","pickedup","returned","cancelled"],
        default:"quotation"
    },
    invoiceStatus:{
        type:String,
        enum:["nothing_to_invoice","to_invoice","fully_invoiced"],
        default:"nothing_to_invoice"
    },
    paymentStatus:{
        type:String,
        enum:["pending","partial","paid"],
        default:"pending"
    },
    isLatePickup:{
        type:Boolean,
        default:false
    },
    pickupTransfer:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Transfer"
    },
    returnTransfer:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Transfer"
    },
    expirationDate:{
        type:Date
    },
    terms:{
        type:String
    },
    qrCode:{
        type:String
    }
},{timestamps:true});

export const RentalOrder=mongoose.model("RentalOrder",rentalOrderSchema);